#!/usr/bin/env python3
import json
import sys
import subprocess
from pathlib import Path

here = Path(__file__).resolve().parent

def run(args, cwd=None, **kwargs):
    args = [str(a) for a in args]
    if cwd:
        kwargs['cwd'] = str(cwd)
    print('+', ' '.join(args))
    return subprocess.run(args, check=True, **kwargs)

[directory_str, out] = sys.argv[1:]
directory = Path(directory_str)
with (directory / 'config.json').open(encoding='utf8') as f:
    config = json.load(f)

tag = 'liquidinvestigations/{}:latest-{}'.format(directory.name, config['arch'])
upstream = directory / 'upstream'
out_name = '{}-{}'.format(directory.name, config['arch'])

if subprocess.run(['which', 'docker']).returncode > 0:
    run(['apt-get', 'update'])
    run(['apt-get', 'install', '-y', 'docker.io'])

if not upstream.is_dir():
    run(['git', 'clone', config['upstream'], upstream])

run(['docker', 'build', '.', '--tag', tag], cwd=directory)

with open(out, 'wb') as f:
    run(['docker', 'save', tag], stdout=f)
