#!/usr/bin/env python3
import json
import sys
import subprocess
from pathlib import Path

here = Path(__file__).resolve().parent
out_dir = Path('/mnt/shared/docker-images')

def run(args, cwd=here, **kwargs):
    return subprocess.run(
        [str(a) for a in args],
        cwd=str(cwd),
        check=True,
        **kwargs
    )

[name] = sys.argv[1:]
tag = 'liquidinvestigations/{}:latest-arm32v6'.format(name)
directory = here / name
upstream = directory / 'upstream'
out_name = '{}-arm32v6'.format(name)
out_path = out_dir / out_name

with (directory / 'meta.json').open(encoding='utf8') as f:
    meta = json.load(f)

run(['apt-get', 'update'])
run(['apt-get', 'install', '-y', 'docker.io'])

if not upstream.is_dir():
    run(['git', 'clone', meta['upstream'], upstream])

run(['docker', 'build', '.', '--tag', tag], cwd=directory)

if not out_dir.is_dir():
    out_dir.mkdir()

with out_path.open('wb') as out:
    run(['docker', 'save', tag], stdout=out)
