#!/usr/bin/env python3
import json
import sys
import tarfile
import subprocess

def run(args, **kwargs):
    args = [str(a) for a in args]
    print('+', ' '.join(args))
    return subprocess.run(args, check=True, **kwargs)

[path] = sys.argv[1:]

image = tarfile.open(path)
with image.extractfile('manifest.json') as f:
    manifest = json.loads(f.read().decode('utf8'))

with open(path, 'rb') as f:
    run(['docker', 'load'], stdin=f)

tags = manifest[0]['RepoTags']
run(['docker', 'push'] + tags)
