#!/usr/bin/env python3
import subprocess
from pathlib import Path

NAME = 'hoover-ui'
UPSTREAM = 'https://github.com/hoover/ui'
TAG = 'liquidinvestigations/{}:latest-arm32v6'.format(NAME)
out_name = '{}-arm32v6'.format(NAME)
here = Path(__file__).resolve().parent
upstream = here / 'upstream'
out_dir = Path('/mnt/shared/docker-images')
out_path = out_dir / out_name

def run(args, cwd=here, **kwargs):
    return subprocess.run(
        [str(a) for a in args],
        cwd=str(cwd),
        check=True,
        **kwargs
    )


run(['apt-get', 'update'])
run(['apt-get', 'install', '-y', 'docker.io'])

if not upstream.is_dir():
    run(['git', 'clone', UPSTREAM, upstream])

run(['docker', 'build', '.', '--tag', TAG])

if not out_dir.is_dir():
    out_dir.mkdir()

with out_path.open('wb') as out:
    run(['docker', 'save', TAG], stdout=out)
